name: Main

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: "shivammathur/setup-php@v2"
        with:
          php-version: "latest"
      - uses: "ramsey/composer-install@v2"
        with:
          working-directory: "UnivaPay"
      - name: Build
        run: cd UnivaPay && tar -cvzf UnivaPay.tar.gz *
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            UnivaPay/UnivaPay.tar.gz
